FROM public.ecr.aws/docker/library/node:18-bullseye

# Variables
ENV DEBIAN_FRONTEND=noninteractive

# Paquetes base
RUN apt-get update && apt-get install -y \
    curl \
    unzip \
    git \
    jq \
    ca-certificates \
    gnupg \
    lsb-release \
    && rm -rf /var/lib/apt/lists/*


# Verificación
RUN node --version \
 && npm --version \